### ISSUE TITLE
AttributeError: 'AudioProcessor' object has no attribute '_denormalize'

### ISSUE THREAD

**Issue by mirfan899** [synesthesiam/docker-mozillatts#20]
I tried to use it on my local machine and getting the following error after successfully building the docker images.

```shell
[INFO] 172.17.0.1 - - [18/Mar/2021 12:19:42] "GET /api/tts?text=how%20are%20you%3F HTTP/1.1" 500 -
[INFO] Synthesizing (41 char(s))...
[INFO] initializing backend espeak-1.48.03
[ERROR] Exception on /api/tts [POST]
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/app/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/tts_web/__main__.py", line 139, in api_tts
    wav_bytes = text_to_wav(text)
  File "/app/tts_web/__main__.py", line 73, in text_to_wav
    line_wav_bytes = synthesizer.synthesize(line)
  File "/app/tts_web/synthesize.py", line 324, in synthesize
    scale_factors=self.scale_factors,
  File "/app/tts_web/synthesize.py", line 59, in tts
    mel_postnet_spec = ap._denormalize(mel_postnet_spec.T).T
AttributeError: 'AudioProcessor' object has no attribute '_denormalize'
```

I'm using a custom model.

**Comment by d33tah** [comment]
Still a problem for me on a1991f64b366052055cf8af248b850275e73327d.

```
 > ls model/en/
checkpoint_130000.pth.tar  checkpoint_130000_tf_2.3rc0.tflite  checkpoint_130000_tf.pkl  config.json  scale_stats.n
```
